ALTER TABLE transactions
ADD COLUMN IF NOT EXISTS audit_decision TEXT NULL,
ADD COLUMN IF NOT EXISTS audit_risk_score DOUBLE PRECISION NULL,
ADD COLUMN IF NOT EXISTS audit_reason TEXT NULL,
ADD COLUMN IF NOT EXISTS audit_provider TEXT NULL,
ADD COLUMN IF NOT EXISTS audit_model TEXT NULL,
ADD COLUMN IF NOT EXISTS audited_at TIMESTAMPTZ NULL;

