#!/usr/bin/env bash
set -euo pipefail

export APP_ENV="${APP_ENV:-local}"
export WORKER_NAME="${WORKER_NAME:-notification-worker}"
export RABBITMQ_URL="${RABBITMQ_URL:-amqp://finpharm:finpharm@localhost:5672/}"
export RABBITMQ_EXCHANGE="${RABBITMQ_EXCHANGE:-finpharm.events}"
export RABBITMQ_TRANSACTION_APPROVED_QUEUE="${RABBITMQ_TRANSACTION_APPROVED_QUEUE:-transaction.approved.queue}"
export RABBITMQ_TRANSACTION_APPROVED_ROUTING_KEY="${RABBITMQ_TRANSACTION_APPROVED_ROUTING_KEY:-transaction.approved}"
export RABBITMQ_TRANSACTION_APPROVED_RETRY_QUEUE="${RABBITMQ_TRANSACTION_APPROVED_RETRY_QUEUE:-transaction.approved.retry.queue}"
export RABBITMQ_TRANSACTION_APPROVED_RETRY_ROUTING_KEY="${RABBITMQ_TRANSACTION_APPROVED_RETRY_ROUTING_KEY:-transaction.approved.retry}"
export RABBITMQ_TRANSACTION_APPROVED_DLQ="${RABBITMQ_TRANSACTION_APPROVED_DLQ:-transaction.approved.dlq}"
export RABBITMQ_TRANSACTION_APPROVED_DLQ_ROUTING_KEY="${RABBITMQ_TRANSACTION_APPROVED_DLQ_ROUTING_KEY:-transaction.approved.dlq}"
export RABBITMQ_CONSUMER_TAG="${RABBITMQ_CONSUMER_TAG:-worker.transaction.approved}"
export RABBITMQ_PREFETCH_COUNT="${RABBITMQ_PREFETCH_COUNT:-10}"
export RABBITMQ_MAX_RETRY_COUNT="${RABBITMQ_MAX_RETRY_COUNT:-3}"
export RABBITMQ_RETRY_DELAY_MS="${RABBITMQ_RETRY_DELAY_MS:-5000}"
export WORKER_METRICS_PORT="${WORKER_METRICS_PORT:-9094}"
export SHUTDOWN_TIMEOUT_MS="${SHUTDOWN_TIMEOUT_MS:-7000}"

go run ./services/worker/cmd/worker